### ISSUE TITLE
connect: connection refused Dial: will try again in 2s seconds.

### ISSUE THREAD

**Issue by will-yijinin** [itering/subscan-essentials#117]
I changed WSEndPoint to "wss://rpc.polkadot.io/". Cannot connect.
```
WSEndPoint                = GetEnv("CHAIN_WS_ENDPOINT", "wss://rpc.polkadot.io/")
NetworkNode               = GetEnv("NETWORK_NODE", "polkadot")
```
Throws error:
```
cmd % ./subscan
2021/04/22 20:45:13 start watch filepath: ../configs
2021/04/22 20:45:13 dial tcp [::1]:9944: connect: connection refused Dial: will try again in 2s seconds.
2021/04/22 20:45:15 dial tcp [::1]:9944: connect: connection refused Dial: will try again in 2s seconds.
2021/04/22 20:45:15 dial tcp [::1]:9944: connect: connection refused Dial: will try again in 2.351897628s seconds.
panic: Can not find chain metadata, please check network
	panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/itering/scale.go/types.regCustomKey(0xc000252690, 0x21, 0x47a1b80, 0xc0000a2080)
	/Users/will.shu/go/pkg/mod/github.com/itering/scale.go@v1.0.3/types/customType.go:136 +0x4e5
github.com/itering/scale.go/types.RegCustomTypes(0xc0005303c0)
	/Users/will.shu/go/pkg/mod/github.com/itering/scale.go@v1.0.3/types/customType.go:99 +0x7fb
github.com/itering/substrate-api-rpc.RegCustomTypes(0xc0004ce000, 0x801, 0x802)
	/Users/will.shu/go/pkg/mod/github.com/itering/substrate-api-rpc@v0.3.5/types.go:9 +0x4d
github.com/itering/subscan/internal/service.(*Service).initSubRuntimeLatest.func1(0xc00051e750)
	/Users/will.shu/Desktop/subscan-essentials-master/internal/service/service.go:41 +0x6b
panic(0x4712860, 0x48cd6f0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/itering/subscan/internal/service.(*Service).initSubRuntimeLatest(0xc00051e750)
	/Users/will.shu/Desktop/subscan-essentials-master/internal/service/service.go:62 +0x257
github.com/itering/subscan/internal/service.New(0x10)
	/Users/will.shu/Desktop/subscan-essentials-master/internal/service/service.go:26 +0xa5
main.run()
	/Users/will.shu/Desktop/subscan-essentials-master/cmd/main.go:94 +0x34
main.setupApp.func1(0xc0002d4000, 0x0, 0x0)
	/Users/will.shu/Desktop/subscan-essentials-master/cmd/main.go:48 +0x25
github.com/urfave/cli.HandleAction(0x471bd80, 0x483ba70, 0xc0002d4000, 0xc0002ae2a0, 0x0)
	/Users/will.shu/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0x82
github.com/urfave/cli.(*App).Run(0xc000220340, 0xc000020220, 0x1, 0x1, 0x0, 0x0)
	/Users/will.shu/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:264 +0x5f5
main.main()
	/Users/will.shu/Desktop/subscan-essentials-master/cmd/main.go:32 +0x71
```

**Comment by will-yijinin** [comment]
Update:

I changed to my local polkadot node:
```
WSEndPoint                = GetEnv("CHAIN_WS_ENDPOINT", "wss://localhost:9933/")
```
Throws Error:
```
2021/04/30 10:40:06 tls: first record does not look like a TLS handshake Dial: will try again in 2s seconds.
2021/04/30 10:40:08 tls: first record does not look like a TLS handshake Dial: will try again in 2s seconds.
2021/04/30 10:40:08 tls: first record does not look like a TLS handshake Dial: will try again in 2.218406828s seconds.
```

**Comment by freehere107** [comment]
9933 is HTTP RPC , you use 9944 port

**Comment by will-yijinin** [comment]
@freehere107 Thank you.
