### ISSUE TITLE
WS Error <Http(Token)>: Invalid byte where token is required.

### ISSUE THREAD

**Issue by smithy9901** [itering/subscan-essentials#141]
When I try to connect your api to a WS DOT node, I get an error

```
panic: Can not find chain metadata, please check network
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/itering/scale.go/types.regCustomKey(0xc000296bb0, 0x9, 0xbdbea0, 0xc000624240)
	/go/pkg/mod/github.com/itering/scale.go@v1.0.51/types/customType.go:141 +0x4c9
github.com/itering/scale.go/types.RegCustomTypes(0xc0001998f0)
	/go/pkg/mod/github.com/itering/scale.go@v1.0.51/types/customType.go:104 +0x83c
github.com/itering/substrate-api-rpc.RegCustomTypes(0xc00061c000, 0xa41, 0xc41)
	/go/pkg/mod/github.com/itering/substrate-api-rpc@v0.4.0/types.go:9 +0x4d
github.com/itering/subscan/internal/service.(*Service).initSubRuntimeLatest.func1(0xc0004061d0)
	/subscan/internal/service/service.go:41 +0x60
panic(0xb37dc0, 0xd4dfe0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/itering/subscan/internal/service.(*Service).initSubRuntimeLatest(0xc0004061d0)
	/subscan/internal/service/service.go:62 +0x24b
github.com/itering/subscan/internal/service.New(0x80)
	/subscan/internal/service/service.go:26 +0xa1
main.run()
	/subscan/cmd/main.go:82 +0x34
main.setupApp.func1(0xc00042a160, 0x0, 0x0)
	/subscan/cmd/main.go:37 +0x20
github.com/urfave/cli.HandleAction(0xb47ec0, 0xc8a268, 0xc00042a160, 0xc000400d20, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.(*App).Run(0xc000478000, 0xc0000201e0, 0x1, 0x1, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:264 +0x5dd
main.main()
	/subscan/cmd/main.go:26 +0x71
```

In the DOT node logs I see the following
```
Accepted a new tcp connection from 127.0.0.1:52922.
2021-07-15 15:32:13 WS Error <Http(Token)>: Invalid byte where token is required.
```

**Comment by smithy9901** [comment]
The error went away when I specified localhost instead of 127.0.0.1
