### ISSUE TITLE
How to work with acala mandala?

### ISSUE THREAD

**Issue by imstar15** [itering/subscan-essentials#86]
I am learning to develop the Polkadot parachain and I am building the subscan-essentials project. I can run subscan-essentials now, but I don't know how to configure it to work with acala testnet. Thank you!

**Comment by freehere107** [comment]
@imstar15 hello. you just set ENV CHAIN_WS_ENDPOINT  and  NETWORK_NODE = "acala" , then  add custom type JSON to https://github.com/itering/subscan-essentials/tree/master/configs/source/acala.sjon like https://github.com/itering/scale.go/blob/master/network/acala.json

**Comment by imstar15** [comment]
I can run it, but there is no data in the database. I don't know why.
This is the log:
```
2020/12/12 03:03:21 start watch filepath: ../configs
2020/12/12 03:03:21 - - - - - - - - - - - - - - -
2020/12/12 03:03:21 daemon started
WARN 12/12-03:03:25.517 /Users/star/devlab/subscan-essentials/internal/service/service.go:43 Found unknown type Box<CallOf>
```

My environment:
OS: macOS 11
network: Acala private network, 0.6.2 (https://github.com/AcalaNetwork/Acala/releases/tag/0.6.2)

**Comment by freehere107** [comment]
@imstar15 Are there only these logs?

**Comment by imstar15** [comment]
Yes, there are no more logs.

Both my mysql and redis are configured.

**Comment by freehere107** [comment]
> Yes, there are no more logs.
> 
> Both my mysql and redis are configured.

I try to run only set NETWORK_NODE and CHAIN_WS_ENDPOINT , synchronization is normal, maybe you need to check WebSocket connect

**Comment by imstar15** [comment]
What is your acala private network version?

**Comment by freehere107** [comment]
> What is your acala private network version?
> I configured an acala private network locally

wss://node-6714447553211260928.rz.onfinality.io/ws

**Comment by imstar15** [comment]
I set the following environment variables and restarted. The following error occurred.
```
export CHAIN_WS_ENDPOINT=wss://node-6714447553211260928.rz.onfinality.io/ws
export NETWORK_NODE=acala
```

```
2020/12/14 17:31:54 start watch filepath: ../configs
2020/12/14 17:31:54 - - - - - - - - - - - - - - -
2020/12/14 17:31:54 daemon started
2020/12/14 17:31:56 dial tcp: i/o timeout Dial: will try again in 2s seconds.
2020/12/14 17:31:58 dial tcp: i/o timeout Dial: will try again in 2s seconds.
panic: Can not find chain metadata, please check network
	panic: assignment to entry in nil map

goroutine 5 [running]:
github.com/itering/scale.go/types.regCustomKey(0xc0002eeb10, 0x10, 0x482d100, 0xc0001b2300)
	/Users/star/go/pkg/mod/github.com/itering/scale.go@v0.8.0/types/customType.go:130 +0x2e3
github.com/itering/scale.go/types.RegCustomTypes(0xc00015e570)
	/Users/star/go/pkg/mod/github.com/itering/scale.go@v0.8.0/types/customType.go:99 +0x916
github.com/itering/substrate-api-rpc.RegCustomTypes(0xc0001cc000, 0x33c6, 0x35c6)
	/Users/star/go/pkg/mod/github.com/itering/substrate-api-rpc@v0.2.1/types.go:9 +0x4d
github.com/itering/subscan/internal/service.(*Service).initSubRuntimeLatest.func1(0xc00005bbc0)
	/Users/star/devlab/subscan-essentials/internal/service/service.go:41 +0x60
panic(0x4781980, 0x49a0ce0)
	/usr/local/Cellar/go/1.13/libexec/src/runtime/panic.go:679 +0x1b2
github.com/itering/subscan/internal/service.(*Service).initSubRuntimeLatest(0xc00005bbc0)
	/Users/star/devlab/subscan-essentials/internal/service/service.go:62 +0x25b
github.com/itering/subscan/internal/service.New(0x403599a)
	/Users/star/devlab/subscan-essentials/internal/service/service.go:26 +0xa1
github.com/itering/subscan/internal/observer.doRun(0x7ffeefbff430, 0x9)
	/Users/star/devlab/subscan-essentials/internal/observer/observer.go:88 +0x26
created by github.com/itering/subscan/internal/observer.doAction
	/Users/star/devlab/subscan-essentials/internal/observer/observer.go:73 +0x5ae
```


What is the reason?

**Comment by freehere107** [comment]
Network connection problem

**Comment by imstar15** [comment]
I tried again and got these error logs

**cmd:**
```
export CHAIN_WS_ENDPOINT=wss://node-6714447553211260928.rz.onfinality.io/ws
export NETWORK_NODE=acala
./subscan start substrate
```

**config:**
config/http.toml
```
[server]
    addr = "0.0.0.0:4399"
    timeout = "1s"
```

config/mysql.toml
```
[server]
    addr = "0.0.0.0:4399"
    timeout = "1s"
star@stardeair configs % cat mysql.toml
[conf]
    host = "127.0.0.1"
    user = "root"
    pass = "Rewq1234"
    db   = "subscan"
[api]
	dsn = "?readTimeout=2s&writeTimeout=3s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
[task]
    dsn = "?parseTime=true&loc=Local&charset=utf8mb4,utf8"
[test]
    dsn = "root:@tcp(127.0.0.1)/subscan_test?parseTime=true&loc=Local&charset=utf8mb4,utf8"
```

config/redis.toml
```
[config]
	name = "subscan"
	proto = "tcp"
	addr = "127.0.0.1:27017"
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "1s"
	writeTimeout = "1s"
	idleTimeout = "10s"
```

**log:**
```
2020/12/15 23:09:12 start watch filepath: ../configs
2020/12/15 23:09:12 - - - - - - - - - - - - - - -
2020/12/15 23:09:12 daemon started
WARN 12/15-23:09:16.370 /Users/star/devlab/subscan-essentials/internal/service/service.go:43 Found unknown type Box<CallOf>, Params, wasm::PrefabWasmModule
```

**Comment by freehere107** [comment]
Are there still no other logs? You can upgrade to the latest version and try again.
then add this env 
``export DEPLOY_ENV= prod``

**Comment by imstar15** [comment]
I Changed system from MacOSX to ubuntu 16, and it worked.
Thank you
