### ISSUE TITLE
assignment to entry in nil map

### ISSUE THREAD

**Issue by jadechip** [itering/subscan-essentials#88]
Hi there, I have the subscan api and daemon running in Kubernetes. Logs look nominal but certain requests fail with the following error:

`ERROR 12/15-19:21:01.588 /go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/recovery.go:26 http call panic: POST /api/scan/metadata HTTP/1.1`

Complete stack trace:

```
assignment to entry in nil map
goroutine 101 [running]:
github.com/go-kratos/kratos/pkg/net/http/blademaster.Recovery.func1.1(0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/recovery.go:20 +0xb8
panic(0xb6ddc0, 0xd3ea40)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/itering/subscan/internal/service.(*Service).Metadata(0xc00012b330, 0xc0004e50f0, 0x230000000040e076, 0xc0004e5090)
	/tmp/subscan-essentials/internal/service/common.go:26 +0x9b
github.com/itering/subscan/internal/server/http.metadata(0xc00030e180)
	/tmp/subscan-essentials/internal/server/http/scan.go:14 +0x2d
github.com/go-kratos/kratos/pkg/net/http/blademaster.(*Context).Next(0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/context.go:84 +0x3b
github.com/itering/subscan/internal/middleware.CORS.func1(0xc00030e180)
	/tmp/subscan-essentials/internal/middleware/cors.go:19 +0x556
github.com/go-kratos/kratos/pkg/net/http/blademaster.HandlerFunc.ServeHTTP(0xc789a8, 0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/server.go:72 +0x30
github.com/go-kratos/kratos/pkg/net/http/blademaster.(*Context).Next(0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/context.go:84 +0x3b
github.com/go-kratos/kratos/pkg/net/http/blademaster.(*RateLimiter).Limit.func1(0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/ratelimit.go:51 +0x3bc
github.com/go-kratos/kratos/pkg/net/http/blademaster.HandlerFunc.ServeHTTP(0xc0003cadf0, 0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/server.go:72 +0x30
github.com/go-kratos/kratos/pkg/net/http/blademaster.(*Context).Next(0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/context.go:84 +0x3b
github.com/go-kratos/kratos/pkg/net/http/blademaster.Logger.func1(0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/logger.go:26 +0xde
github.com/go-kratos/kratos/pkg/net/http/blademaster.HandlerFunc.ServeHTTP(0xc77a38, 0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/server.go:72 +0x30
github.com/go-kratos/kratos/pkg/net/http/blademaster.(*Context).Next(0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/context.go:84 +0x3b
github.com/go-kratos/kratos/pkg/net/http/blademaster.Trace.func1(0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/trace.go:38 +0x603
github.com/go-kratos/kratos/pkg/net/http/blademaster.HandlerFunc.ServeHTTP(0xc77a60, 0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/server.go:72 +0x30
github.com/go-kratos/kratos/pkg/net/http/blademaster.(*Context).Next(0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/context.go:84 +0x3b
github.com/go-kratos/kratos/pkg/net/http/blademaster.Recovery.func1(0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/recovery.go:30 +0x4e
github.com/go-kratos/kratos/pkg/net/http/blademaster.HandlerFunc.ServeHTTP(0xc77a58, 0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/server.go:72 +0x30
github.com/go-kratos/kratos/pkg/net/http/blademaster.(*Context).Next(0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/context.go:84 +0x3b
github.com/go-kratos/kratos/pkg/net/http/blademaster.(*Engine).handleContext(0xc00060b200, 0xc00030e180)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/server.go:327 +0x402
github.com/go-kratos/kratos/pkg/net/http/blademaster.(*Engine).ServeHTTP(0xc00060b200, 0xd5a7a0, 0xc0002c8000, 0xc0000b6100)
	/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/server.go:490 +0x152
net/http.serverHandler.ServeHTTP(0xc000568460, 0xd5a7a0, 0xc0002c8000, 0xc0000b6100)
	/usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc000274140, 0xd5cf60, 0xc0004a4440)
	/usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2962 +0x35c
```

I'm actively trying to pinpoint the issue, if anyone has any ideas, that would be greatly appreciated :)

**Comment by jadechip** [comment]
Another thing I just noticed in the daemon logs:
`daemon: Resource temporarily unavailable` 
not sure what could be causing this either.

**Comment by freehere107** [comment]
@jadechip hey, you can check https://github.com/itering/subscan-essentials/blob/287ad0baa74d3b1c55b34049ff5bcc0c1a2b84b0/util/env.go#L13 ,  This error is usually caused by network problems

**Comment by jadechip** [comment]
@freehere107 thank you for the quick response. It does seem to be related to web sockets. Earlier I was trying to connect to my own local Polkadot node running in the same k8 cluster, I tried changing the CHAIN_WS_ENDPOINT env var to wss://crab.darwinia.network but the error still persists. Also, from the substrate_log file I see the following: 
`ERROR 12/16-08:01:16.572 /tmp/subscan-essentials/internal/service/subscribe.go:39 read: read tcp 10.X.XXX.XX:48170->172.XX.XX.X:443: use of closed network connection`

**Comment by freehere107** [comment]
@jadechip This means that there is still a WebSocket connection problem

**Comment by jadechip** [comment]
This issue has been resolved. By logging out an error in the Metadata function in common.go we discovered that the websocket issues were a red herring, and the service was silently failing due to the port not being included in the Redis endpoint. Thanks for your help!
