### ISSUE TITLE
 ERROR  EMFILE: too many open files

### ISSUE THREAD

**Issue by lovesh** [itering/subscan-essentials#91]
I am on Kubuntu and have `ulimit` set to 16384. But when I run `yarn dev` from `ui` directory, I get the following errors
```
 ERROR  EMFILE: too many open files, watch '....../subscan-essentials/ui/node_modules/@nuxtjs/axios/lib/plugin.js'                                                                      23:18:56

  at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
  at Proxy.watch (fs.js:1525:34)
  at createFsWatchInstance (node_modules/chokidar/lib/nodefs-handler.js:119:15)
  at setFsWatchListener (node_modules/chokidar/lib/nodefs-handler.js:166:15)
  at NodeFsHandler._watchWithNodeFs (node_modules/chokidar/lib/nodefs-handler.js:331:14)
  at NodeFsHandler._handleFile (node_modules/chokidar/lib/nodefs-handler.js:395:23)
  at NodeFsHandler._addToNodeFs (node_modules/chokidar/lib/nodefs-handler.js:628:21)
  at async node_modules/chokidar/index.js:445:21
  at async Promise.all (index 0)


 ERROR  EMFILE: too many open files, watch '.........../subscan-essentials/ui/nuxt.config.js'                                                                                                23:18:56

  at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
  at Proxy.watch (fs.js:1525:34)
  at createFsWatchInstance (node_modules/chokidar/lib/nodefs-handler.js:119:15)
  at setFsWatchListener (node_modules/chokidar/lib/nodefs-handler.js:166:15)
  at NodeFsHandler._watchWithNodeFs (node_modules/chokidar/lib/nodefs-handler.js:331:14)
  at NodeFsHandler._handleFile (node_modules/chokidar/lib/nodefs-handler.js:395:23)
  at NodeFsHandler._addToNodeFs (node_modules/chokidar/lib/nodefs-handler.js:628:21)
  at async node_modules/chokidar/index.js:445:21
  at async Promise.all (index 0)


 WARN  Error from chokidar (............./subscan-essentials/ui/.nuxt): Error: EMFILE: too many open files, watch '............./subscan-essentials/ui/.nuxt'                       23:18:56

....
.....

 ERROR  EMFILE: too many open files, watch '............./subscan-essentials/ui/node_modules/@nuxt/vue-app/template/pages/index.vue'                                                           01:52:34

  at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
  at Proxy.watch (fs.js:1525:34)
  at createFsWatchInstance (node_modules/chokidar/lib/nodefs-handler.js:119:15)
  at setFsWatchListener (node_modules/chokidar/lib/nodefs-handler.js:166:15)
  at NodeFsHandler._watchWithNodeFs (node_modules/chokidar/lib/nodefs-handler.js:331:14)
  at NodeFsHandler._handleFile (node_modules/chokidar/lib/nodefs-handler.js:395:23)
  at NodeFsHandler._addToNodeFs (node_modules/chokidar/lib/nodefs-handler.js:628:21)


 ERROR  EMFILE: too many open files, watch '........./subscan-essentials/ui/node_modules/@nuxt/vue-app/template/views/loading'                                                             01:52:34

  at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
  at Proxy.watch (fs.js:1525:34)
  at createFsWatchInstance (node_modules/chokidar/lib/nodefs-handler.js:119:15)
  at setFsWatchListener (node_modules/chokidar/lib/nodefs-handler.js:166:15)
  at NodeFsHandler._watchWithNodeFs (node_modules/chokidar/lib/nodefs-handler.js:331:14)
  at NodeFsHandler._handleDir (node_modules/chokidar/lib/nodefs-handler.js:559:19)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async NodeFsHandler._addToNodeFs (node_modules/chokidar/lib/nodefs-handler.js:608:16)

```

Is this error acceptable and if yes whats a reasonable value for `ulimit`

**Comment by carlhong** [comment]
I don't get this error under mac os, maybe this link would help https://www.imakewebsites.ca/posts/2018/03/06/node.js-too-many-open-files-and-ulimit/

**Comment by lovesh** [comment]
I raised ulimit to 65536 and it works then.

**Comment by noxxxxxxxx** [comment]
<img width="487" alt="bug" src="https://user-images.githubusercontent.com/37919656/194222490-c2e89093-0816-455c-b05b-292cbda8681c.png">

Same error when running build command.
